//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ems.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long Id { get; set; }
        public string EmpName { get; set; }
        public string Contact { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> DepId { get; set; }
        public string Gender { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
